In [1]:
import torch
import torchvision.models as models

In [2]:
from bestfitting.protein_clean.src.net import _init_paths
from bestfitting.protein_clean.src.net import densenet
from bestfitting.protein_clean.src.config import config

run on Wooseoks-MacBook-Pro.local
run on Wooseoks-MacBook-Pro.local


In [13]:
import os
opj = os.path.join
from copy import deepcopy

In [4]:
pretrained_file = opj(config.PRETRAINED_DIR, densenet.model_names['class_densenet121_large_dropout'])
net = densenet.class_densenet121_large_dropout(num_classes=28, in_channels=4, pretrained_file=pretrained_file)

In [5]:
weights = opj(config.RESULT_DIR, 'models/external_crop1024_focal_slov_hardlog_clean_class_densenet121_large_dropout_i1536_aug2_5folds/fold0/final.pth')
net.load_state_dict(torch.load(weights)['state_dict'])

<All keys matched successfully>

In [6]:
import numpy as np

In [7]:
net = net.eval()
net.training = False

In [30]:
inputs = torch.randn(16, 4, 128, 128)
i1 = deepcopy(inputs)


In [26]:
outputs = net.forward(inputs)

training False


In [27]:
np.allclose(net(inputs).data.numpy(), outputs.data.numpy())

training False


False

In [35]:
net(inputs)[0]

training False


tensor([-3.2260e+02, -1.9432e+00, -4.9589e+01, -1.0377e+03, -1.0299e+03,
        -6.4345e+02, -1.2496e+03, -6.0285e+02, -4.0241e+03, -2.8873e+03,
        -2.6121e+03, -6.9811e+02, -1.3769e+03, -7.0021e+02,  1.2574e+02,
        -3.3160e+03, -5.5438e+02, -9.1323e+02, -6.7333e+02, -5.1991e+02,
        -1.5476e+03, -1.1753e+03, -1.0710e+03, -6.0162e+02, -1.5002e+03,
        -4.0567e+02, -1.0395e+03, -1.8811e+03], grad_fn=<SelectBackward>)

In [36]:
net(i1)[0]

training False


tensor([-3.2260e+02, -1.9432e+00, -4.9589e+01, -1.0377e+03, -1.0299e+03,
        -6.4345e+02, -1.2496e+03, -6.0285e+02, -4.0241e+03, -2.8873e+03,
        -2.6121e+03, -6.9811e+02, -1.3769e+03, -7.0021e+02,  1.2574e+02,
        -3.3160e+03, -5.5438e+02, -9.1323e+02, -6.7333e+02, -5.1991e+02,
        -1.5476e+03, -1.1753e+03, -1.0710e+03, -6.0162e+02, -1.5002e+03,
        -4.0567e+02, -1.0395e+03, -1.8811e+03], grad_fn=<SelectBackward>)

In [45]:
a = np.arange(5)

In [46]:
b = deepcopy(a)

In [47]:
a[0] = 5

In [49]:
a

array([5, 1, 2, 3, 4])

In [50]:
b

array([0, 1, 2, 3, 4])

In [ ]:
print(torch.__version__)

In [ ]:
outputs[0]